# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

before_all do
  # Install with `fastlane add_plugin semaphore`
  setup_semaphore
end

platform :ios do
  lane :build do
    build_app(scheme: 'TallestTowers', 
      skip_package_ipa: true,
      skip_archive: true,
      skip_codesigning: true,
      xcargs: "ONLY_ACTIVE_ARCH=YES", # since for this demo we skip_codesigning, the build will be done for a simulator, and since XCode 12, this means arm64, thus build failing. Semaphore is running on x86 chips.
      silent: true,
      clean: true
    )
  end

  lane :test do
    run_tests(scheme: 'TallestTowers', devices: ['iPhone 11 Pro'], prelaunch_simulator: true)
  end

  lane :screenshots do
    snapshot
  end
end
